import { GitHubRepository } from '@/lib/types';

export const DEMO_REPOSITORIES: GitHubRepository[] = [
  {
    id: 101001,
    name: 'next-awesome-ui',
    fullName: 'demo/next-awesome-ui',
    owner: { login: 'demo', avatarUrl: 'https://github.com/github.png' },
    description: 'A collection of polished UI components built with Next.js and Tailwind.',
    stars: 8423,
    forks: 512,
    openIssuesCount: 24,
    language: 'TypeScript',
    topics: ['ui', 'nextjs', 'tailwind', 'components'],
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/demo/next-awesome-ui',
    hasGoodFirstIssues: true,
    isActive: true,
  },
  {
    id: 101002,
    name: 'react-hooks-lib',
    fullName: 'demo/react-hooks-lib',
    owner: { login: 'demo', avatarUrl: '' },
    description: 'Small, focused React hooks for common patterns and performance.',
    stars: 4210,
    forks: 210,
    openIssuesCount: 11,
    language: 'TypeScript',
    topics: ['react', 'hooks', 'library'],
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/demo/react-hooks-lib',
    hasGoodFirstIssues: false,
    isActive: true,
  },
  {
    id: 101003,
    name: 'docs-template',
    fullName: 'demo/docs-template',
    owner: { login: 'demo', avatarUrl: '' },
    description: 'Opinionated documentation template and tooling for OSS projects.',
    stars: 1890,
    forks: 86,
    openIssuesCount: 7,
    language: 'JavaScript',
    topics: ['docs', 'developer-experience'],
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/demo/docs-template',
    hasGoodFirstIssues: true,
    isActive: false,
  },
  {
    id: 101004,
    name: 'api-server-starter',
    fullName: 'demo/api-server-starter',
    owner: { login: 'demo', avatarUrl: '' },
    description: 'Minimal API server starter with tests and Dockerfile.',
    stars: 3200,
    forks: 140,
    openIssuesCount: 18,
    language: 'Go',
    topics: ['api', 'go', 'server'],
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/demo/api-server-starter',
    hasGoodFirstIssues: false,
    isActive: true,
  },
  {
    id: 101005,
    name: 'data-visuals',
    fullName: 'demo/data-visuals',
    owner: { login: 'demo', avatarUrl: '' },
    description: 'Reusable visualization components for dashboards and reports.',
    stars: 950,
    forks: 42,
    openIssuesCount: 3,
    language: 'TypeScript',
    topics: ['charts', 'visualization', 'react'],
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/demo/data-visuals',
    hasGoodFirstIssues: true,
    isActive: true,
  },
  {
    id: 101006,
    name: 'cli-toolkit',
    fullName: 'demo/cli-toolkit',
    owner: { login: 'demo', avatarUrl: '' },
    description: 'Utilities and helpers for building fast CLIs in Node.js.',
    stars: 600,
    forks: 30,
    openIssuesCount: 2,
    language: 'JavaScript',
    topics: ['cli', 'developer-tools'],
    updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/demo/cli-toolkit',
    hasGoodFirstIssues: false,
    isActive: false,
  },
];
