// Mock data for frontend demo mode
import { GitHubIssue, GitHubRepository } from '../types';

export const MOCK_ISSUES: GitHubIssue[] = [
  {
    id: 1,
    number: 123,
    title: 'Add dark mode support to navigation component',
    body: 'We need to implement dark mode for the navigation bar. This should include proper color schemes and transitions.',
    state: 'open',
    htmlUrl: 'https://github.com/opensrc/awesome-ui/issues/123',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 5,
    labels: [
      { id: 1, name: 'good first issue', color: '7057ff', description: 'Good for newcomers' },
      { id: 2, name: 'enhancement', color: 'a2eeef' },
      { id: 3, name: 'ui', color: 'bfd4f2' },
    ],
    author: {
      login: 'johndoe',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=johndoe',
    },
    repository: {
      owner: 'opensrc',
      name: 'awesome-ui',
      fullName: 'opensrc/awesome-ui',
      description: 'A beautiful UI component library',
      stars: 12400,
      language: 'TypeScript',
    },
  },
  {
    id: 2,
    number: 456,
    title: 'Fix memory leak in data fetching hook',
    body: 'The useDataFetch hook has a memory leak when unmounting. Need to cleanup subscriptions properly.',
    state: 'open',
    htmlUrl: 'https://github.com/community/react-hooks/issues/456',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 8,
    labels: [
      { id: 4, name: 'bug', color: 'd73a4a' },
      { id: 5, name: 'help wanted', color: '008672' },
      { id: 6, name: 'performance', color: 'fbca04' },
    ],
    author: {
      login: 'janedoe',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=janedoe',
    },
    repository: {
      owner: 'community',
      name: 'react-hooks',
      fullName: 'community/react-hooks',
      description: 'Collection of useful React hooks',
      stars: 25800,
      language: 'TypeScript',
    },
  },
  {
    id: 3,
    number: 789,
    title: 'Update documentation for new API endpoints',
    body: 'We added 3 new API endpoints but the documentation is missing. Need to add examples and usage guides.',
    state: 'open',
    htmlUrl: 'https://github.com/clouddev/api-gateway/issues/789',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 3,
    labels: [
      { id: 7, name: 'documentation', color: '0075ca' },
      { id: 8, name: 'good first issue', color: '7057ff' },
    ],
    author: {
      login: 'devuser',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=devuser',
    },
    repository: {
      owner: 'clouddev',
      name: 'api-gateway',
      fullName: 'clouddev/api-gateway',
      description: 'High-performance API Gateway',
      stars: 8950,
      language: 'Go',
    },
  },
  {
    id: 4,
    number: 321,
    title: 'Implement keyboard shortcuts for editor',
    body: 'Add common keyboard shortcuts like Ctrl+S for save, Ctrl+Z for undo, etc.',
    state: 'open',
    htmlUrl: 'https://github.com/devstudio/devtools-pro/issues/321',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 12,
    labels: [
      { id: 9, name: 'feature', color: 'a2eeef' },
      { id: 10, name: 'accessibility', color: 'e99695' },
      { id: 11, name: 'good first issue', color: '7057ff' },
    ],
    author: {
      login: 'codemaster',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=codemaster',
    },
    repository: {
      owner: 'devstudio',
      name: 'devtools-pro',
      fullName: 'devstudio/devtools-pro',
      description: 'Professional developer tools suite',
      stars: 18900,
      language: 'Rust',
    },
  },
  {
    id: 5,
    number: 654,
    title: 'Add TypeScript types for configuration',
    body: 'The config file needs proper TypeScript type definitions for better IDE support.',
    state: 'open',
    htmlUrl: 'https://github.com/opensrc/awesome-ui/issues/654',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 6,
    labels: [
      { id: 12, name: 'good first issue', color: '7057ff' },
      { id: 13, name: 'typescript', color: '3178c6' },
    ],
    author: {
      login: 'typesenjoyer',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=typesenjoyer',
    },
    repository: {
      owner: 'opensrc',
      name: 'awesome-ui',
      fullName: 'opensrc/awesome-ui',
      description: 'A beautiful UI component library',
      stars: 12400,
      language: 'TypeScript',
    },
  },
  {
    id: 6,
    number: 987,
    title: 'Improve error messages for validation',
    body: 'Current error messages are not user-friendly. Need better explanations and suggestions.',
    state: 'open',
    htmlUrl: 'https://github.com/community/react-hooks/issues/987',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 4,
    labels: [
      { id: 14, name: 'enhancement', color: 'a2eeef' },
      { id: 15, name: 'ux', color: 'bfd4f2' },
      { id: 16, name: 'help wanted', color: '008672' },
    ],
    author: {
      login: 'uxdesigner',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=uxdesigner',
    },
    repository: {
      owner: 'community',
      name: 'react-hooks',
      fullName: 'community/react-hooks',
      description: 'Collection of useful React hooks',
      stars: 25800,
      language: 'TypeScript',
    },
  },
  {
    id: 7,
    number: 445,
    title: 'Add Python client library for API',
    body: 'We need an official Python SDK for easier integration with our API.',
    state: 'open',
    htmlUrl: 'https://github.com/clouddev/api-gateway/issues/445',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 15,
    labels: [
      { id: 17, name: 'feature', color: 'a2eeef' },
      { id: 18, name: 'help wanted', color: '008672' },
    ],
    author: {
      login: 'pythonista',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pythonista',
    },
    repository: {
      owner: 'clouddev',
      name: 'api-gateway',
      fullName: 'clouddev/api-gateway',
      description: 'High-performance API Gateway',
      stars: 8950,
      language: 'Go',
    },
  },
  {
    id: 8,
    number: 234,
    title: 'Optimize rendering performance for large datasets',
    body: 'When rendering 1000+ items, the UI becomes sluggish. Need virtualization.',
    state: 'open',
    htmlUrl: 'https://github.com/analytics/data-viz/issues/234',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 9,
    labels: [
      { id: 19, name: 'performance', color: 'fbca04' },
      { id: 20, name: 'bug', color: 'd73a4a' },
    ],
    author: {
      login: 'perf_hunter',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=perfhunter',
    },
    repository: {
      owner: 'analytics',
      name: 'data-viz',
      fullName: 'analytics/data-viz',
      description: 'Interactive data visualization library',
      stars: 19200,
      language: 'JavaScript',
    },
  },
  {
    id: 9,
    number: 556,
    title: 'Add CI/CD pipeline configuration examples',
    body: 'Include example configs for GitHub Actions, GitLab CI, and Jenkins.',
    state: 'open',
    htmlUrl: 'https://github.com/devstudio/devtools-pro/issues/556',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 7,
    labels: [
      { id: 21, name: 'documentation', color: '0075ca' },
      { id: 22, name: 'good first issue', color: '7057ff' },
    ],
    author: {
      login: 'devops_guru',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=devopsguru',
    },
    repository: {
      owner: 'devstudio',
      name: 'devtools-pro',
      fullName: 'devstudio/devtools-pro',
      description: 'Professional developer tools suite',
      stars: 18900,
      language: 'Rust',
    },
  },
  {
    id: 10,
    number: 112,
    title: 'Support for custom themes and color schemes',
    body: 'Allow users to create and apply custom color themes to the UI.',
    state: 'open',
    htmlUrl: 'https://github.com/opensrc/awesome-ui/issues/112',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 18,
    labels: [
      { id: 23, name: 'feature', color: 'a2eeef' },
      { id: 24, name: 'help wanted', color: '008672' },
    ],
    author: {
      login: 'theme_wizard',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=themewizard',
    },
    repository: {
      owner: 'opensrc',
      name: 'awesome-ui',
      fullName: 'opensrc/awesome-ui',
      description: 'A beautiful UI component library',
      stars: 12400,
      language: 'TypeScript',
    },
  },
  {
    id: 11,
    number: 678,
    title: 'Add unit tests for authentication module',
    body: 'The auth module lacks proper test coverage. We need unit tests for all functions.',
    state: 'open',
    htmlUrl: 'https://github.com/clouddev/api-gateway/issues/678',
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 5,
    labels: [
      { id: 25, name: 'testing', color: 'ededed' },
      { id: 26, name: 'good first issue', color: '7057ff' },
    ],
    author: {
      login: 'qa_master',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qamaster',
    },
    repository: {
      owner: 'clouddev',
      name: 'api-gateway',
      fullName: 'clouddev/api-gateway',
      description: 'High-performance API Gateway',
      stars: 8950,
      language: 'Go',
    },
  },
  {
    id: 12,
    number: 890,
    title: 'Migrate to latest React version',
    body: 'Update all dependencies and code to work with React 19.',
    state: 'open',
    htmlUrl: 'https://github.com/community/react-hooks/issues/890',
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    commentsCount: 22,
    labels: [
      { id: 27, name: 'refactoring', color: 'fbca04' },
      { id: 28, name: 'breaking change', color: 'd73a4a' },
    ],
    author: {
      login: 'react_ninja',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=reactninja',
    },
    repository: {
      owner: 'community',
      name: 'react-hooks',
      fullName: 'community/react-hooks',
      description: 'Collection of useful React hooks',
      stars: 25800,
      language: 'TypeScript',
    },
  },
];

export const MOCK_REPOSITORIES: GitHubRepository[] = [
  {
    id: 1,
    name: 'awesome-ui',
    fullName: 'opensrc/awesome-ui',
    owner: {
      login: 'opensrc',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=opensrc',
    },
    description: 'A beautiful UI component library for modern web apps with 100+ customizable components',
    stars: 12400,
    forks: 1850,
    openIssuesCount: 43,
    language: 'TypeScript',
    topics: ['ui', 'components', 'react', 'typescript', 'design-system'],
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/opensrc/awesome-ui',
    hasGoodFirstIssues: true,
    isActive: true,
  },
  {
    id: 2,
    name: 'react-hooks',
    fullName: 'community/react-hooks',
    owner: {
      login: 'community',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=community',
    },
    description: 'Collection of 50+ useful React hooks for common use cases',
    stars: 25800,
    forks: 3200,
    openIssuesCount: 28,
    language: 'TypeScript',
    topics: ['react', 'hooks', 'javascript', 'frontend', 'productivity'],
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/community/react-hooks',
    hasGoodFirstIssues: true,
    isActive: true,
  },
  {
    id: 3,
    name: 'api-gateway',
    fullName: 'clouddev/api-gateway',
    owner: {
      login: 'clouddev',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=clouddev',
    },
    description: 'High-performance API Gateway with rate limiting, auth, and caching',
    stars: 8950,
    forks: 1250,
    openIssuesCount: 18,
    language: 'Go',
    topics: ['api', 'gateway', 'microservices', 'golang', 'performance'],
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/clouddev/api-gateway',
    hasGoodFirstIssues: false,
    isActive: true,
  },
  {
    id: 4,
    name: 'ml-toolkit',
    fullName: 'ailab/ml-toolkit',
    owner: {
      login: 'ailab',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ailab',
    },
    description: 'Machine learning toolkit with pre-trained models and easy-to-use APIs',
    stars: 34200,
    forks: 5600,
    openIssuesCount: 156,
    language: 'Python',
    topics: ['machine-learning', 'ai', 'deep-learning', 'neural-networks', 'tensorflow'],
    updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/ailab/ml-toolkit',
    hasGoodFirstIssues: true,
    isActive: true,
  },
  {
    id: 5,
    name: 'devtools-pro',
    fullName: 'devstudio/devtools-pro',
    owner: {
      login: 'devstudio',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=devstudio',
    },
    description: 'Professional developer tools suite with debugging, profiling, and testing',
    stars: 18900,
    forks: 2100,
    openIssuesCount: 67,
    language: 'Rust',
    topics: ['devtools', 'debugging', 'profiling', 'rust', 'cli'],
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/devstudio/devtools-pro',
    hasGoodFirstIssues: true,
    isActive: true,
  },
  {
    id: 6,
    name: 'game-engine',
    fullName: 'gameworks/game-engine',
    owner: {
      login: 'gameworks',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=gameworks',
    },
    description: 'Open-source 2D/3D game engine with visual editor and physics',
    stars: 42000,
    forks: 6800,
    openIssuesCount: 234,
    language: 'C++',
    topics: ['game-engine', 'graphics', 'physics', 'game-dev', '3d'],
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/gameworks/game-engine',
    hasGoodFirstIssues: true,
    isActive: true,
  },
  {
    id: 7,
    name: 'blockchain-node',
    fullName: 'cryptochain/blockchain-node',
    owner: {
      login: 'cryptochain',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cryptochain',
    },
    description: 'Scalable blockchain node implementation with smart contract support',
    stars: 15600,
    forks: 2900,
    openIssuesCount: 89,
    language: 'Rust',
    topics: ['blockchain', 'cryptocurrency', 'smart-contracts', 'web3', 'distributed'],
    updatedAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/cryptochain/blockchain-node',
    hasGoodFirstIssues: false,
    isActive: true,
  },
  {
    id: 8,
    name: 'mobile-framework',
    fullName: 'mobiledev/mobile-framework',
    owner: {
      login: 'mobiledev',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mobiledev',
    },
    description: 'Cross-platform mobile framework for iOS and Android',
    stars: 28400,
    forks: 4200,
    openIssuesCount: 112,
    language: 'Dart',
    topics: ['mobile', 'flutter', 'ios', 'android', 'cross-platform'],
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/mobiledev/mobile-framework',
    hasGoodFirstIssues: true,
    isActive: true,
  },
  {
    id: 9,
    name: 'data-viz',
    fullName: 'analytics/data-viz',
    owner: {
      login: 'analytics',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=analytics',
    },
    description: 'Interactive data visualization library with 30+ chart types',
    stars: 19200,
    forks: 2400,
    openIssuesCount: 54,
    language: 'JavaScript',
    topics: ['dataviz', 'charts', 'graphics', 'analytics', 'd3'],
    updatedAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/analytics/data-viz',
    hasGoodFirstIssues: true,
    isActive: true,
  },
  {
    id: 10,
    name: 'security-scanner',
    fullName: 'secops/security-scanner',
    owner: {
      login: 'secops',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=secops',
    },
    description: 'Automated security vulnerability scanner for web applications',
    stars: 11300,
    forks: 1600,
    openIssuesCount: 31,
    language: 'Python',
    topics: ['security', 'scanner', 'vulnerabilities', 'pentest', 'devsecops'],
    updatedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    pushedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    htmlUrl: 'https://github.com/secops/security-scanner',
    hasGoodFirstIssues: false,
    isActive: true,
  },
];
